name: release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  call-build-workflow:
    uses: ./.github/workflows/build.yml

  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'cashapp/android-cash-paykit-sdk'
    needs: call-build-workflow

    steps:
      - name: Publish Artifacts
        # TODO pass in the maven version as a param?
        run: |
          ./gradlew clean publish --stacktrace

        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY }}


          # TODO we could consider creating a github release
          # from zipline https://github.com/cashapp/zipline/blob/trunk/.github/workflows/release.yaml#LL111C7-L130C22
